"""Report generation for SEC analysis results."""

from datetime import datetime
from typing import Dict, Any
import json

from .config import Config


class ReportGenerator:
    """Generate formatted reports from risk analysis results."""
    
    def __init__(self, config: Config):
        self.config = config
    
    def generate_report(self, analysis_results: Dict[str, Any], 
                       ticker: str, report_type: str) -> str:
        """Generate a comprehensive analysis report."""
        
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        
        report = f"""
# SEC Risk Analysis Report

**Company:** {ticker.upper()}
**Report Type:** {report_type}
**Analysis Date:** {timestamp}
**Generated by:** SEC Analyzer v{self.config.__class__.__module__.split('.')[-1]}

---

## Executive Summary

**Overall Risk Level:** {analysis_results.get('overall_risk_level', 'Unknown')}
**Overall Risk Score:** {analysis_results.get('overall_risk_score', 'N/A')}

{self._generate_executive_summary(analysis_results)}

---

## Risk Assessment by Category

{self._generate_risk_categories_section(analysis_results)}

---

## Key Risk Insights

{self._generate_key_insights_section(analysis_results)}

---

## Regulatory Implications

{self._generate_regulatory_section(analysis_results)}

---

## Monitoring Recommendations

{self._generate_monitoring_section(analysis_results)}

---

## Technical Details

**Analysis Method:** AI-powered analysis using Strands Agents framework
**Models Used:** {self.config.bedrock_model}
**Data Sources:** SEC EDGAR filings
**Analysis Timestamp:** {analysis_results.get('analysis_timestamp', 'N/A')}

---

## Disclaimer

This analysis is generated by AI agents and should be used as a supplementary tool for risk assessment. 
All findings should be validated through additional due diligence and expert review. This report is 
intended for internal use only and contains preliminary risk assessments that may require further 
investigation.

---

*Report generated by SEC Analyzer*
"""
        
        return report
    
    def _generate_executive_summary(self, results: Dict[str, Any]) -> str:
        """Generate executive summary section."""
        
        risk_level = results.get('overall_risk_level', 'Unknown')
        key_insights = results.get('key_insights', [])
        
        summary = f"""
The analysis of SEC filings indicates a **{risk_level}** overall risk profile for this entity. 
"""
        
        if key_insights:
            summary += f"""
The primary areas of concern identified include:

"""
            for i, insight in enumerate(key_insights[:3], 1):
                summary += f"{i}. {insight}\n"
        
        return summary
    
    def _generate_risk_categories_section(self, results: Dict[str, Any]) -> str:
        """Generate risk categories section."""
        
        risk_categories = results.get('risk_categories', {})
        
        if not risk_categories:
            return "Risk category analysis is not available in the current results."
        
        section = ""
        
        for category, data in risk_categories.items():
            level = data.get('level', 'Unknown')
            score = data.get('score', 'N/A')
            summary = data.get('summary', 'No detailed analysis available')
            
            section += f"""
### {category.replace('_', ' ').title()}

**Risk Level:** {level}  
**Risk Score:** {score}

{summary}

"""
        
        return section
    
    def _generate_key_insights_section(self, results: Dict[str, Any]) -> str:
        """Generate key insights section."""
        
        insights = results.get('key_insights', [])
        
        if not insights:
            return "No specific risk insights were identified in the analysis."
        
        section = ""
        
        for i, insight in enumerate(insights, 1):
            section += f"{i}. {insight}\n\n"
        
        return section
    
    def _generate_regulatory_section(self, results: Dict[str, Any]) -> str:
        """Generate regulatory implications section."""
        
        risk_level = results.get('overall_risk_level', 'Unknown').lower()
        
        if risk_level == 'high' or risk_level == 'critical':
            return """
Based on the identified risk profile, this entity may warrant:

- Enhanced supervisory attention and monitoring
- More frequent examination cycles
- Detailed review of risk management practices
- Potential enforcement actions if deficiencies are confirmed
- Coordination with other regulatory agencies as appropriate

The identified risks should be evaluated in the context of the institution's size, 
complexity, and systemic importance.
"""
        elif risk_level == 'medium':
            return """
The moderate risk profile suggests:

- Standard supervisory monitoring with attention to identified risk areas
- Review of risk management practices during next examination
- Monitoring of trends in key risk indicators
- Engagement with management on risk mitigation strategies
"""
        else:
            return """
The current risk assessment suggests standard supervisory oversight is appropriate, 
with continued monitoring of the identified risk factors through regular supervisory processes.
"""
    
    def _generate_monitoring_section(self, results: Dict[str, Any]) -> str:
        """Generate monitoring recommendations section."""
        
        risk_categories = results.get('risk_categories', {})
        
        recommendations = [
            "Regular review of SEC filings for emerging risk disclosures",
            "Monitoring of key financial metrics and ratios",
            "Assessment of risk management framework effectiveness"
        ]
        
        # Add category-specific recommendations
        if 'credit_risk' in risk_categories:
            recommendations.append("Enhanced monitoring of credit quality metrics and loan loss provisions")
        
        if 'operational_risk' in risk_categories:
            recommendations.append("Review of operational risk controls and cybersecurity measures")
        
        if 'liquidity_risk' in risk_categories:
            recommendations.append("Monitoring of liquidity ratios and funding source diversification")
        
        section = ""
        for i, rec in enumerate(recommendations, 1):
            section += f"{i}. {rec}\n"
        
        return section
    
    def generate_json_report(self, analysis_results: Dict[str, Any]) -> str:
        """Generate JSON format report for programmatic use."""
        
        report_data = {
            "metadata": {
                "generated_at": datetime.now().isoformat(),
                "generator": "SEC Analyzer",
                "version": "0.1.0"
            },
            "analysis": analysis_results
        }
        
        return json.dumps(report_data, indent=2, default=str)